language: cpp
- os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-8.2
    script:
      - cmake --version
      - mkdir ./stinky_17_release
      - cd ./stinky_17_release
      - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release ..
      - cmake -E time cmake --build .
