language: cpp

addons: &gcc8
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - cmake

matrix:
  include:
    - env: GCC_VERSION=8 BUILD_TYPE=Release CPP=17
      os: linux
      dist: trusty
      sudo: require
      addons: *gcc8

before_script:
  export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"

script:
  - cmake --version
  - mkdir ./stinky_17_release
  - cd ./stinky_17_release
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release ..
  - cmake -E time cmake --build .
